### ISSUE TITLE
TypeClass of RecordTypes, error message doesn't indicate which field is invalid

### ISSUE THREAD

**Issue by yrns** [sanctuary-js/sanctuary-def#75] opened 2016-05-31 23:38 UTC
I'm just getting started with this - forgive me if my issue is already understood, or I'm doing it wrong. I have a function that takes a `TypeClass` of two possible `RecordType`'s. One of the fields is invalid in my passed type. I get a "type-class constraint violation". I know I'm passing the correct type, but the error message isn't clear which field is off. I realize the test for my `TypeClass` just returns false and doesn't discern between "you passed the right type but something is wrong with it" versus "you just passed the wrong type." I'd like to know which fields are invalid. I was confused at first because I thought I had incorrectly defined my `TypeClass`.

**Comment by davidchambers** [comment] 2016-06-01 00:19
> One of the fields is invalid in my passed type. I get a "type-class constraint violation". I know I'm passing the correct type, but the error message isn't clear which field is off.

The problem is that type-class predicates are applied before type predicates ([source][1]). Perhaps type classes should provide `validate :: a -> Either String a` rather than `test :: a -> Boolean` so we could indicate why a particular value doesn't satisfy the requirements of the specified type class.

Could you post the definitions of the type class and the two record types? I'm wondering whether it's possible to express your constraints without using a type class.


[1]: https://github.com/sanctuary-js/sanctuary-def/blob/v0.6.0/index.js#L933-L952

**Comment by yrns** [comment] 2016-06-01 00:50
> Perhaps type classes should provide `validate :: a -> Either String a` ...

That seems useful to me. This is roughly what I have:

```javascript
export const Atom = $.RecordType({
    v: $.Object,
    vf: $.Function,
    watches: $.Object,
})

export const Cursor = $.RecordType({
    v: Atom,
    vf: $.Function,
    lens: $.Function,
    path: $.String,
})

export const RefType = $.TypeClass(
    'RefType', anyPass([Atom._test, Cursor._test]))
```

**Comment by davidchambers** [comment] 2016-06-01 01:12
Thanks for providing these definitions, @yrns.

Are you defining a type class because you wish to define functions which operate on RefType values but you don't want to permit heterogeneous arrays containing both Atom values and Cursor values? Another option is to define a RefType type (rather than type class), but to omit this from your environment. You'd then be able to use `RefType` in type definitions while still disallowing heterogeneous arrays. This wouldn't address your problem, though, since a nullary type defined as the union of two record types will not indicate the invalid field.

This leads to an interesting question: how *would* one present a type error for a type which is a union of multiple record types? Would we display one error message for each type in the union? In this case, one error message indicating why the value is not a member of the Atom type, and one indicating why it is not a member of the Cursor type. That could be confusing.

**Comment by yrns** [comment] 2016-06-01 02:51
In working through this I fixed some inconstistencies in my code, so this has been helpful already. I believe what I currently have should be working, but I'm getting an "unexpected type" error in `equalTypes`. My type class does not have a `type` field. I will drum up a demo of this.

> Are you defining a type class because you wish to define functions which operate on RefType values but you don't want to permit heterogeneous arrays containing both Atom values and Cursor values?

I only wanted to define a function that takes an Atom or a Cursor. I'm not using arrays of either yet, so I didn't specifically attempt this in this way to preclude heterogeneous arrays. I just thought a type class was the proper way to go. I see that I could just make a nullary type.

> This leads to an interesting question: how would one present a type error for a type which is a union of multiple record types?

I had hoped that because the value I was passing was an object with a field `@@type` of "Cursor" that it would magically know my intention. In a validation function I would check that, I suppose. If the error listed out why each type failed, at least I'd have more information. I agree that could turn into a nasty error message, especially with records of records and so on.

**Comment by davidchambers** [comment] 2016-06-09 18:41
What would you like to see happen next, @yrns?

**Comment by DanielFGray** [comment] 2018-04-13 01:36
>Jun 9, 2016
>What would you like to see happen next?

The suspense is killing me right now.

**Comment by davidchambers** [comment] 2020-01-08 12:53
This issue is not actionable, so I will close it.

**Closed by davidchambers** 2020-01-08 12:53 UTC
